### ISSUE TITLE
Can not work？

### ISSUE THREAD

**Issue by sky-fly97** [samliu0631/Light-Field-Simulation#1]
Hello，when I run the Demo/RunSimulateLytroImage.m， it can not work.
`Searching for files [ *.xml ] in ../Data/Lytro
引用了不存在的字段 'Children'。

出错 GetLensGridFormXML>Read_Calibration (line 68)
    CalibStruct.Diameter            = str2double(RaytrixXML.Children(4).Children.Data);`

**Comment by sky-fly97** [comment]
![image](https://user-images.githubusercontent.com/55578436/125156630-07151480-e199-11eb-9eab-5516424736e0.png)

![image](https://user-images.githubusercontent.com/55578436/125156622-fa90bc00-e198-11eb-9632-e6cb0f9e2160.png)

**Comment by samliu0631** [comment]
Thanks for your feedback. To be honest, I reran my codes and did not encounter the same errors you have mentioned. By the way, which version of  Matlab is your current IDE and have you ever removed  or modified  the Lytro.xml under the directory /Data/Lytro. What the platform are you using(Windows or Linux)?

**Comment by sky-fly97** [comment]
> Thanks for your feedback. To be honest, I reran my codes and did not encounter the same errors you have mentioned. By the way, which version of Matlab is your current IDE and have you ever removed or modified the Lytro.xml under the directory /Data/Lytro. What the platform are you using(Windows or Linux)?

Thanks for your quick reply,  my Matlab is R2019a under windows. And I have not changed Lytro.xml under the directory /Data/Lytro..
At first, I run the AddToolboxPath.m, then run the Demo/RunSimulateLytroImage.m, but it prompt me that there is no xml2struct， so I download the xml2struct.m from https://www.mathworks.com/matlabcentral/fileexchange/28518-xml2struct, and put it at Demo folder. That's what happened in the end.

**Comment by samliu0631** [comment]
Hi，sky-fly97. Sorry for the late reply. I have added the xml2struct.m file under the  directory ".\MyPlenopticTool\Utility". You can download the latest version  of the codes and give it a try. If you have any questions, feel free to let me know. Best wishes.

**Comment by sky-fly97** [comment]
> Hi，sky-fly97. Sorry for the late reply. I have added the xml2struct.m file under the directory ".\MyPlenopticTool\Utility". You can download the latest version of the codes and give it a try. If you have any questions, feel free to let me know. Best wishes.

Thanks！ The program can run normally, but after running for more than ten minutes, it finally got this result.
![image](https://user-images.githubusercontent.com/55578436/125236214-2a190300-e316-11eb-9274-6cc38e836327.png)

**Comment by samliu0631** [comment]
Hi! The output results are under the folder /Data/Lytro. Besides, you can change the simulated image size ( Line 76 and 77 in RunSimulateLytroImage.m) by modifying the following codes.
InfoBag.pixelY = 100; InfoBag.pixelX = 100;
What's more. I have updated the parameter setting in RunSimulateLytroImage.m, you can have a try.
